name: FLIPtheIndustry
favicon: null
layout_spectrum: 0.6333433140534908
typography_spectrum: 0.11610231548547745
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.46847512340173125
  lightness: 0.203466328792274
  saturation: 0.9678662875667214
  rhythmicContrast: 0.8536893562413752
purpose: []
